[package]
name = "day-12"
version = "0.1.0"
edition = "2021"

[dependencies]
id-arena = { version = "2.2.1", features = ["rayon"] }
itertools = "0.12.0"
nom = "7.1.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
