[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
nom = "7.1.3"
pathfinding = "4.6.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
